### PR TITLE
Fix Github repository name

### PR DESCRIPTION
**Pull request by nhoizey**
I think this should have been set to "savedata" when split from "netinfo"

### CODE REVIEW

**Comment by nhoizey** [comment]
I thought I had a w3.org account, but it looks like I can't connect to link my Github account.

@yoavweiss do you have any recommendation to fix this? If it's complicated, feel free to close this PR and make the change (if relevant) yourself.

**Comment by yoavweiss** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by nhoizey** [comment]
Is Black Speech the official language here? 😅

**Comment by yoavweiss** [comment]
> Is Black Speech the official language here? 😅

yes 💍

**Comment by yoavweiss** [comment]
I think you can follow [this link](https://www.w3.org/users/myprofile/connectedaccounts) to link your accounts. (But it's not strictly required for this change)

Thanks for catching the bad link! :)

**Comment by nhoizey** [comment]
I can't connect to this link for now, but I just changed my password, so it might need some time to sync the account.

You're welcome! 👍

**Comment by nhoizey** [comment]
I still can't connect, I don't understand, there is not error message… 🤷‍♂️

**Comment by yoavweiss** [comment]
@dontcallmedom halp! :)

**Comment by dontcallmedom** [comment]
hey @nhoizey can you follow up by email to dom@w3.org to help debug this?

(in any case, since you're not a participant in the WICG, this wouldn't have helped, but let's figure that bug out :)

**Comment by nhoizey** [comment]
@dontcallmedom while I was writing a mail with detailed steps of my multiple attempts, I saw that connecting on w3.org required my username instead of my e-mail address.

I should read error messages more often… 😅

Sorry to have wasted a little of your time!

**Pull request merged**
